services:

  postgres_etheria:
    image: postgres:17-alpine
    container_name: postgres_etheria
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: EtheriaGlobal
    ports:
      - "5432:5432"
    volumes:
      - ./Scripts/Etheria Global:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_central:
    image: postgres:17-alpine
    container_name: postgres_central
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: RepositorioCentralCaso2
    ports:
      - "5433:5432"
    volumes:
      - ./ETL/Scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.4
    container_name: mysql_dynamic
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: DynamicBrands
    ports:
      - "3306:3306"
    volumes:
      - ./Scripts/Dynamic Brands:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl:
    build: ./ETL
    container_name: etl_process
    depends_on:
      postgres_etheria:
        condition: service_healthy
      postgres_central:
        condition: service_healthy
      mysql:
        condition: service_healthy
    command: ["python", "procesoETL.py"]
